name: Run tests
on:
  pull_request:
  merge_group:

jobs:
  # Label of the container job
  container-job:
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      couchdb:
        # Docker Hub image
        image: couchdb:3.3.2
        # Provide user and password for couchdb
        env:
          COUCHDB_USER: admin
          COUCHDB_PASSWORD: password123

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync with main
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git fetch origin main:main
          git rebase main
        shell: bash

      - name: Start server by running docker-compose
        run: make up
        shell: bash

      - name: Install pre-commit
        run: pip install pre-commit
        shell: bash

      - name: Run pre-commit on all files
        run: pre-commit run -a -v
        shell: bash

      - name: Call tests
        run: make test
        shell: bash

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: garibaldiviolin/super-development-platform

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
